version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      KC_HOSTNAME: http://localhost/auth
      KC_HTTP_RELATIVE_PATH: /auth
#      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
  
  backend:
    build: ./api
    hostname: api
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
    networks:
      - app-network
    depends_on:
      - keycloak
      - frontend

networks:
  app-network:
    driver: bridge
    
volumes:
  postgres_data:
    driver: local